# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RdDTHXVI2lfymTV_MHN5otf6ab4QlyBi
"""

from time import sleep
n1 = int(input("Digite um numero"))
n2 = int(input("Digite um segundo numero"))
esco = 0 
while esco != 5:
  print('=-'*10)
  print('''\033[1;95mMenu \n[1] soma
[2] multiplicação
[3] maior
[4] novos numeros
[5] sair do programa ''')
  sleep(0.5)
  esco = int(input("QUal sua escolha ?"))
  print("=-"*10)
  if esco == 1:
    soma = n1 + n2
    print("A soma da {} + {} Sera {}".format(n1,n2,soma))
  elif esco == 2: 
    multi = n1*n2
    print("{} X {} Resultado {}".format(n1,n2,multi))
  elif esco == 3:
    if n1 > n2:
      maior = n1
    else:
      maior =2      
  elif esco == 4:
    n1 = int(input("Digite um numero"))
    n2= int (input("Digite outro numero"))
  elif esco == 5:
      print("Finaliazando o progrema em")
      print ("3")
      sleep(0.5)
      print ("2")
      sleep(0.5)
      print("1")
      sleep (0.5)
  else:
    print("Opção invalida tente novamente")
print("Programa finalizado")